### ISSUE TITLE
Use `torchinfo` instead of custom `utils.count_params()`

### ISSUE THREAD

**Issue by elcorto** [elcorto/2024-thrill-school-machine-learning#5]
* [x] `02_convnets.py`
* [x] `04_autoencoders.py`
* [x] `05_representationlearning.py`

Do this once #4 is merged, since there we have a new `utils.model_summary()` wrapper for `torchinfo.summary()`.

**Comment by codingS3b** [comment]
the first bullet point should be addressed with #15
